---
title: 'Exercises-1: Intro to R- vectors'
author: "Nathan Green, Imperial College London"
date: "07/09/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## The console

Type the following with the correct operator

1. 3 plus 10
2. 6 times 12
3. What is 4 to the power 7?

4. Type 3 + then
press `Enter`,
press `Enter`,
press `Enter`!

Whats happening?

press `Esc`


## Assigning values

1. Assign the value 100 to `x` using two different syntax

2. Assign the value 21 times `x` to `y` and print to console in one line of code.

3. Now change the value of `x` to 200. What happens to the value of `y`?


## Functions

1. Take the logarithm (natural base) of 10 by assigning 10 as an argument and calling the correct function. What value does it return?

2. What other log base functions are there?

3. Take the reverse function to get back to 10.

HINT: use the help documentation in the Help pane by calling `?` or `help()`


## Multiple argument

1. Use the `rep()` function to repeat the same numbers in a vector.
HINT: Look at the help document.

2. Output to the console the number 1 five times.

3. Write the function with the argument for the number of times to repeat (5) first and 1 second.

4. Use the `rep()` function to repeat the numbers 1,2 five times.

5. Change the arguments so that the total length of the output vector is length 5 with alternating numbers.

6. Change the arguments so that the total length of the output vector is length 5 but with all 1's together and all 2's together.


## Variables

1. Which of these are numbers? Which are words? How can you tell?

```
1
"1"
"one"
```


## Vectors

1. How many dimensions does a vector have?

2. Consider a vector:

`x <- c(4,6,5,7,10,9,4,15)`

What is the value of:

`c(4,6,5,7,10,9,4,15) < 7`

a. `TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE`

b. `TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE`

c. `FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE`

d. `TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE`

e. `TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE`

 
3. Consider two vectors:

`p <- c (3, 5, 6, 8)`
and

`q <- c (3, 3, 3)`

What is the value of:

`p+q`

a. `6, 8, 6, 8`

b. `6, 8, 0, 0`

c. `6, 8, NA, NA`

d. `3, 5, 6, 8 Warning message: In p+q : longer object length is not a multiple of shorter object length`

e. `6, 8, 9, 11`

4. If

`Age <- c(22, 25, 18, 20)`
`Name <- c("James", "Mathew", "Olivia", "Stella")`
`Gender <- c("M", "M", "F", "F")`

then what is the R code for getting the following output

```
##   Age   Name Gender
## 1  22  James      M
## 2  25 Mathew      M
```

a.

`DataFrame = data.frame(c(Age), c(Name), c(Gender))`

`subset(DataFrame, Gender == "M")`

b.

`DataFrame = data.frame(c(Age),c(Name),c(Gender))`

`subset(Gender=="M"), eval=FALSE` 

c.

`DataFrame = data.frame(Age,Name,Gender)`

`subset(DataFrame,Gender=="M")`

d.

`DataFrame = data.frame(c(Age,Name,Gender))`

`subset(DataFrame,Gender=="M")`
 


5. If `z <- 0:9` then what is the output from the following R-statements:

```
digits <- as.character(z)
as.integer(digits)
```

a. `Error in subset. object 'z' not found`

b. `0, 1, 2, 3, 4, 5, 6, 7, 8, 9`

c. `"NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA"`

d. `"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"`

e. `0, 0, 0, 0, 0, 0, 0, 0, 0`


6. Consider the vector `x <- c(1,2,3,4)`.
What is the value of k for:

`(x+2)[(!is.na(x)) & x > 0] -> k`

a. `1, 2, 3, 4`

b. `1, 4, 9, 16`

c. `Error: object 'k' not found`

d. `3, 4, 5, 6`

e. `numeric(0)`

 
7. Consider the AirPassenger data set

`data(AirPassengers)`


Which statement will produce the following output?

`##  [1] 112 118 132 129 121 135 148 148 136 119 104 118`

a. `AirPassengers[time(AirPassengers) >= 1949 & time(AirPassengers) < 1950, 12]`

b. `AirPassengers[AirPassengers >= 1949 & AirPassengers < 1950]`

c. `AirPassengers[time(AirPassengers) >= 1949 & time(AirPassengers) < 1950]`

d. `AirPassengers[AirPassengers >= 1949 & AirPassengers < 1950, 12]`

e. `c[[1]]`


8. If `x <- c(2, 4, 6, 8)` and `y <- c(TRUE, TRUE, FALSE, TRUE)`

What is the value of `sum(x[y])`?

a. `20`

b. `8`

c. `14`

d. `NA`


9. Consider the vector `x <- c(34, 56, 55, 87, NA, 4, 77, NA, 21, NA, 39)`.

Which R-statement will count the number of NA values in x?

a. `count(is.na(X))`

b. `length(is.na(x))`

c. `sum(is.na(x))`

d. `count(!is.na(x))`

e. `sum(!is.na(x))`


10. How many dimensions does a matrix have?

```
1 2 3 4 5
2 3 4 5 6
3 4 5 6 7
4 5 6 7 8
```

11. If the below matrix is named $M$ what is value $M_{34}$? How do you print it to screen?

```
1 2 3 4 5
2 3 4 5 6
3 4 5 6 7
4 5 6 7 8
```

[https://www.r-exercises.com/2015/10/09/vector-exercises/]
