---
title: 'Exercises-1: Intro to R - Logical vectors'
author: "Nathan Green, Imperial College London"
date: "07/09/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Before you start, enter the following code to assign sample data set

```
data <- mtcars
```


1.
Use logical operators to output only those rows of  data  where column  `mpg`  is between 15 and 20 (excluding 15 and 20).

2.
Use logical operators to output only those rows of  data  where column  `cyl`  is equal to 6 and column  am  is not 0.

3.
Use logical operators to output only those rows of  data  where column  `gear`  or  `carb`  has the value 4.

4.
Use logical operators to output only the even rows of  data.

5.
Use logical operators and change every fourth element in column  `mpg`  to 0.

6.
Output only those rows of  data  where columns  `vs`  and  `am`  have the same value 1, solve this without using  `==`  operator.

7.
`(TRUE + TRUE) * FALSE`, what does this expression evaluate to and why?

8.
Output only those rows of  `data`  where at least  `vs`  or  `am`  have the value 1, solve this without using  `==`  or  `!=`.

9.
Explain the difference between  `|` ,  `||` ,  `&`  and  `&&`.

10.
Change all values that are 0 in the column  `am`  in  `data`  to 2.

11.
Add 2 to every element in the column  `vs`  without using numbers.

12.
Output only those rows of  `data`  where  `vs`  and  `am`  have different values, solve this without using  `==`  or  `!=`.
HINT: see `xor()`

[https://www.r-exercises.com/2015/11/25/logical-vectors-and-operators/]
