---
title: 'Exercises-1: Intro to R - Binding'
author: "Nathan Green, Imperial College London"
date: "07/09/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These exercies use the `cbind()` and `rbind()` functions. Read their help documents first.

1.
Create matrices from the vectors below, by binding them column-wise.
Is it possible in all cases? Why not?

a. `r a <- 1:5 ; b <- 1:5`
b. `a <- 1:5 ; b <- c('1', '2', '3', '4', '5')`
c. `a <- 1:5 ; b <- 1:4; c <- 1:3`


2.
Repeat exercise 1, binding vectors row-wise instead of column-wise while avoiding any row names.

3.
Bind the following matrices column-wise. First, without using R, write down whether binding the matrices is actually possible.

a. `a <- matrix(1:12, ncol=4); b <- matrix(21:35, ncol=5)`
b. `a <- matrix(1:12, ncol=4); b <- matrix(21:35, ncol=3)`
c. `a <- matrix(1:39, ncol=3); b <- matrix(LETTERS, ncol=2)`


4.
Bind the matrix `a <- matrix(1:1089, ncol=33)` to itself, column-wise, 5 times HINT: Avoid using `cbind()` to obtain an efficient solution. Various solutions are possible.

5.
Try to create new data frames from the data frames below, by binding them column-wise.
First, without using R, write down whether binding the data frames is actually possible.

a. `a <- data.frame(v1=1:5, v2=LETTERS[1:5]) ; b <- data.frame(var1=6:10, var2=LETTERS[6:10])`
b. `a <- data.frame(v1=1:6, v2=LETTERS[1:6]) ; b <- data.frame(var1=6:10, var2=LETTERS[6:10])`

6.
Try to create new data frames from the data frames below, by binding them row-wise. Is it always possible?

a. `a <- data.frame(v1=1:5, v2=LETTERS[1:5]) ; b <- data.frame(v1=6:10, v2=LETTERS[6:10])`
b. `a <- data.frame(v1=1:6, v2=LETTERS[1:6]) ; b <- data.frame(v2=6:10, v1=LETTERS[6:10])`

7. Use `cbind()` to add vector `v3 <- 1:5` as a new variable to the data frame created in exercise 6b.

Reorder the columns of this data frame, as follows: `v1, v3, v2`.

8.
Consider again the matrices of exercise 3b. Use both `cbind()` and `rbind()` to bind both matrices column-wise, adding `NA` for empty cells.

9.
Consider again the data frames of exercise 5b. Use both `cbind()` and `rbind()` to bind both matrices column-wise, adding `NA` for empty cells.


[https://www.r-exercises.com/2015/11/25/logical-vectors-and-operators/]
